# Generated by Django 3.0.4 on 2020-07-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option2_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option3_counts',
            field=models.IntegerField(default=0),
        ),
    ]
